version: '3'

services:
    nifi-container:
        image: apache/nifi:1.16.1
        container_name: nifi-service
        restart: always
        ports:
            - 8443:8443/tcp
            - 8080:8080/tcp
        environment:
            - SINGLE_USERCREDENTIALS_USERNAME=admin
            - SINGLE_USERCREDENTIALS_PASSWORD=nifipassword
        volumes:
            - "./sqljdbc_12.2/cht/mssql-jdbc-12.2.0.jre8.jar:/opt/jdbc/drivers/mssql-jdbc-12.2.0.jre8.jar"
            - "./sqljdbc_12.2/cht/mssql-jdbc-12.2.0.jre11.jar:/opt/jdbc/drivers/mssql-jdbc-12.2.0.jre11.jar"
            - "./dataset/:/tmp/dataset/"
        networks:
            - nifi-network

    nifi-registry-container:
        image: apache/nifi-registry:1.16.1
        container_name: nifi-registry-service
        restart: always
        ports:
            - 18080:18080/tcp
        networks:
            - nifi-network

networks:
    nifi-network:
